spring:
  main:
    banner-mode: off
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: conecta-reparo
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      auto-commit: false
  flyway:
    schemas: ${SCHEMAS}
    default-schema: ${DEFAULT_SCHEMA}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SPRING_SERVER_PORT}
logging:
  level:
    root: WARN
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG
  file:
    name: ./logs/app.log
    max-size: 10MB
    total-size-cap: 100MB
    max-history: 7

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, env, threaddump, mappings
  endpoint:
    health:
      show-details: always

# CAN CREATE RANDOM ATTRIBUTES TO BE REFERENCED INSIDE YOU APP
# ANY NAME WILL SERVE ITS PURPOSE
storage:
  upload-default: ./uploads # ${storage.upload-default} to access internally